export {default as LoginBg} from "./food/pexels-ella-olsson-1640777.jpg"
export {default as Logo} from "./food/logo.png"
export {default as Avatar} from "./food/avatar.png"
export {default as Mango} from "./food/f1.png"
export {default as Delivery} from "./food/delivery.png"
export {default as HeroBg} from "./food/heroBg.png"
export {default as Bill} from "./food/r1.png"
export {default as Picture} from "./food/pexels-ella-olsson-1640777.jpg"
